source ~/.vundler.vim

set number
set bg=dark
syntax on
set noswapfile
autocmd BufWritePre * %s/\s\+$//e
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
set mouse=a
set esckeys
set ttimeout
set ttimeoutlen=100
set bs=2

let g:multi_cursor_exit_from_visual_mode=0
let g:multi_cursor_exit_from_insert_mode=0

colorscheme gruvbox

function! s:find_git_root()
  return system('git rev-parse --show-toplevel 2> /dev/null')[:-2]
endfunction

command! ProjectFiles execute 'Files' s:find_git_root()
nnoremap <silent> <C-p> :ProjectFiles<CR>

nnoremap <silent> <C-o> :NERDTreeToggle<CR>
