set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'kana/vim-fakeclip'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plugin 'junegunn/fzf.vim'
Plugin 'morhetz/gruvbox'
Plugin 'bling/vim-airline'

call vundle#end()            " required
filetype plugin indent on    " required'

set number
set bg=dark
syntax on
set noswapfile
autocmd BufWritePre * %s/\s\+$//e
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
set mouse=a
set esckeys
set ttimeout
set ttimeoutlen=100

colorscheme gruvbox
