source ~/.plugins.vim

source ~/.vimrc.portable

"cursorline for focused pane
augroup CursorLine
  au!
  au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
  au WinLeave * setlocal nocursorline
augroup END

"multiple cursors
let g:multi_cursor_exit_from_visual_mode=0
let g:multi_cursor_exit_from_insert_mode=0

"colours
colorscheme gruvbox

"splits
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
set splitbelow
set splitright

"fzf
function! s:find_git_root()
  return system('git rev-parse --show-toplevel 2> /dev/null')[:-2]
endfunction

command! ProjectFiles execute 'Files' s:find_git_root()
nnoremap <silent> <C-p> :ProjectFiles<CR>

"NERDTree
nnoremap <silent> <C-o> :NERDTreeToggle<CR>

"YCM
let g:ycm_key_list_stop_completion = ['<C-y>', '<CR>']

"NERDCommenter
let g:NERDDefaultAlign = 'left'

"Goyo
let g:goyo_width = 120
